# Converting data from MATLAB


Connect to a running MATLAB

In [1]:
import matlab.engine

In [2]:
m = matlab.engine.connect_matlab()

Call MATLAB function to create data. Note that scalars are converted directly

In [3]:
r = m.rand(1)
r

0.8147236863931789

Arrays are not converted as directly. Try different data types.

In [4]:
x = m.pascal(3)
#x = m.randi(10,3, 2)
x

matlab.double([[1.0,1.0,1.0],[1.0,2.0,3.0],[1.0,3.0,6.0]])

Access data. Again, scalars are converted.

In [5]:
x[0][0]

1.0

Try accessing a row

In [6]:
x[1]

matlab.double([1.0,2.0,3.0])

In [7]:
list(x[1])

[1.0, 2.0, 3.0]

x

Access the data in the MATLAB array

In [8]:
x._data

array('d', [1.0, 1.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 6.0])

Convert to a list (with original matrix orientation)

In [9]:
c = [[] for i in range(x.size[0])]
for (i, item) in enumerate(x._data):
    c[i % x.size[0]].append(item)
print(c)

# c = [list(x._data[i::x.size[0]]) for i in range(x.size[0])]
# print(c)

[[1.0, 1.0, 1.0], [1.0, 2.0, 3.0], [1.0, 3.0, 6.0]]


Alternatively

In [10]:
import numpy as np

In [11]:
y = np.array(x)
print(y)

[[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 6.]]


You could access just the data part of the MATLAB array for efficiency (may need to reshape)

In [12]:
y = np.array(x._data)
print(y)

[1. 1. 1. 1. 2. 3. 1. 3. 6.]


In [13]:
x

matlab.double([[1.0,1.0,1.0],[1.0,2.0,3.0],[1.0,3.0,6.0]])

In [14]:
y = np.array(x._data).reshape(x.size[::-1])
print(y)

[[1. 1. 1.]
 [1. 2. 3.]
 [1. 3. 6.]]


In [15]:
#m.exit()

For 2d arrays:
np.array(x._data).reshape(x.size[::-1]).T

To adapt it to N dimensional arrays is to use the order parameter of np.reshape() :

np_x = np.array(x._data).reshape(x.size, order='F')

https://www.mathworks.com/help/matlab/matlab_external/handle-data-returned-from-matlab-to-python.html

https://stackoverflow.com/questions/30013853/convert-matlab-double-array-to-python-array

https://stackoverflow.com/questions/34155829/how-to-efficiently-convert-matlab-engine-arrays-to-numpy-ndarray